version: 2.1

jobs:
  initial-job:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "Initialize Job"
          command: "echo Initialize"
  build-job:
    docker:
      - image: cimg/go:1.18-node
    steps:
      - checkout
      - run:
          name: "Build Job"
          command: >-
            cd ./client
            npm install
            npm run build
            cd ./server
            timeout 25 go run server-side.go

workflows:
  say-hello-workflow:
    jobs:
      - initial-job
      - build-job
