version: 2.1

jobs:
  first-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "First Job"
          command: "echo first-job; touch test.txt; pwd; ls -a"
  second-job:
    docker:
      - image: cimg/go:1.18
    steps:
      - run:
          name: "Second Job"
          command: "echo second-job; pwd; ls -a"

workflows:
  say-hello-workflow:
    jobs:
      - first-job
      - second-job
